"""
RAG Generation Pipeline
-----------------------
Orchestrates intent classification, retrieval, context assembly,
optional web search fallback, and LLM generation into a single async
call that returns a structured GenerationResponse.

Latency optimisation strategy
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1. Intent classification and retrieval execute in PARALLEL via asyncio.gather
   — both need only the query string, so neither blocks the other.
2. Intent classification uses heuristics first (sub-ms), LLM only on
   ambiguous cases with max_tokens=20.
3. Context is token-budgeted per intent — no wasted LLM context.
4. Web search (when triggered) runs before the main generation call and
   is bounded by a 5 s timeout.
5. The main generation call uses temperature=0.1 and a focused max_tokens
   so the model doesn't over-generate.
6. Streaming is exposed as generate_stream() for low time-to-first-token
   in the API layer.

Output format
~~~~~~~~~~~~~
The model is instructed to emit a JSON object (via response_format) with
keys: answer, confidence, follow_up_questions.
Sources are attached from the retrieval/web results, not generated by the LLM,
preventing hallucinated citations.
"""

from __future__ import annotations

import asyncio
import json
import logging
from typing import AsyncIterator, Optional

from openai import AsyncOpenAI

from config.settings import settings
from retrieval.models import RetrievalResult
from .models import Confidence, GenerationRequest, GenerationResponse, Intent, Source
from .prompts import get_prompt, get_system_prompt, active_version
from .intent_classifier import IntentClassifier
from .context_builder import build_context, retrieval_confidence
from .web_search import build_web_search_query, should_use_web_search, web_search

logger = logging.getLogger(__name__)


# ── Response parser ────────────────────────────────────────────────────────────

def _parse_llm_output(raw: str) -> tuple[str, Confidence, list[str]]:
    """
    Extract answer, confidence, and follow_up_questions from the LLM's JSON.
    Returns safe defaults on parse failure.
    """
    try:
        # Strip accidental markdown fences if the model added them
        cleaned = raw.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.split("```")[1]
            if cleaned.startswith("json"):
                cleaned = cleaned[4:]
        parsed = json.loads(cleaned)
        answer = parsed.get("answer", raw)
        confidence = Confidence(parsed.get("confidence", "medium"))
        follow_ups = parsed.get("follow_up_questions", [])[:3]
        return answer, confidence, follow_ups
    except Exception as exc:
        logger.warning(f"Failed to parse LLM JSON output ({exc}); using raw text.")
        return raw, Confidence.LOW, []


# ── Main generator ─────────────────────────────────────────────────────────────

class RAGGenerator:
    """
    End-to-end RAG generation pipeline.

    Parameters
    ----------
    retriever : HybridRetriever (or any object with a .retrieve() method)
        Used for dense+BM25+rerank retrieval.
    vllm_base_url : str
        Base URL of the vLLM OpenAI-compatible server.
    model : str
        vLLM model name (e.g. "Qwen/Qwen2.5-7B-Instruct").
    """

    # Score below which web search fallback is triggered
    WEB_SEARCH_SCORE_THRESHOLD = 0.25

    def __init__(
        self,
        retriever,
        vllm_base_url: str = settings.vllm_base_url,
        model: str = settings.vllm_model,
    ) -> None:
        self._retriever = retriever
        self._model = model
        self._client = AsyncOpenAI(
            base_url=vllm_base_url,
            api_key="not-needed",   # vLLM does not enforce auth by default
        )
        self._intent_classifier = IntentClassifier(self._client, model)

    # ── Retrieval wrapper (sync → async) ──────────────────────────────────────

    async def _retrieve(
        self,
        query: str,
        source_filter: Optional[str],
        jurisdiction_filter: Optional[str],
    ) -> list[RetrievalResult]:
        """Run retriever in a thread pool to avoid blocking the event loop."""
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            None,
            lambda: self._retriever.retrieve(
                query,
                source_filter=source_filter,
                jurisdiction_filter=jurisdiction_filter,
            ),
        )

    # ── Public API ─────────────────────────────────────────────────────────────

    async def generate(self, request: GenerationRequest) -> GenerationResponse:
        """
        Full RAG generation pipeline.

        Steps
        -----
        1. Run intent classification + retrieval in parallel.
        2. Build token-budgeted context from retrieval results.
        3. Decide whether web search fallback is needed.
        4. Execute web search (if needed) with domain-augmented query.
        5. Assemble user prompt and call vLLM.
        6. Parse structured JSON output into GenerationResponse.
        """
        query              = request.query
        source_filter      = request.source_filter
        jurisdiction_filter = request.jurisdiction_filter

        # ── Step 1: Parallel intent classification + retrieval ─────────────
        intent_task    = self._intent_classifier.classify(query)
        retrieval_task = self._retrieve(query, source_filter, jurisdiction_filter)

        intent, results = await asyncio.gather(intent_task, retrieval_task)

        logger.info(
            f"generate | intent={intent} | retrieval_hits={len(results)} | query='{query[:80]}'"
        )

        # ── Step 2: Build context ──────────────────────────────────────────
        context_str, sources = build_context(results, intent)
        top_score = retrieval_confidence(results)
        retrieval_used = bool(context_str)

        # ── Step 3: Web search decision ────────────────────────────────────
        use_web = should_use_web_search(top_score, intent.value, self.WEB_SEARCH_SCORE_THRESHOLD)
        web_query: Optional[str] = None
        web_sources: list[Source] = []

        if use_web:
            web_query = build_web_search_query(query, intent.value)
            web_formatted, web_raw = await web_search(web_query)
            logger.info(f"Web search | query='{web_query}' | results={len(web_raw)}")
        else:
            web_formatted = ""

        # ── Step 4: Assemble user prompt ───────────────────────────────────
        pv = active_version()
        if context_str and not use_web:
            user_prompt = get_prompt("user_with_context", pv).format(
                context_blocks=context_str,
                query=query,
            )
        elif use_web and web_formatted:
            user_prompt = get_prompt("user_with_web", pv).format(
                web_query=web_query,
                web_results=web_formatted,
                query=query,
            )
        else:
            user_prompt = get_prompt("user_no_context", pv).format(query=query)

        system_prompt = get_system_prompt(intent.value, pv)
        logger.debug(f"generate | prompt_version={pv}")

        # ── Step 5: LLM call ───────────────────────────────────────────────
        llm_response = await self._client.chat.completions.create(
            model=self._model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_prompt},
            ],
            max_tokens=settings.llm_max_tokens,
            temperature=settings.llm_temperature,
            response_format={"type": "json_object"},
        )

        raw_output = llm_response.choices[0].message.content or ""

        # ── Step 6: Parse & return ─────────────────────────────────────────
        answer, confidence, follow_ups = _parse_llm_output(raw_output)

        return GenerationResponse(
            intent=intent,
            answer=answer,
            sources=sources,
            follow_up_questions=follow_ups,
            confidence=confidence,
            used_web_search=use_web and bool(web_formatted),
            web_search_query=web_query,
            retrieval_used=retrieval_used,
        )

    async def generate_stream(
        self, request: GenerationRequest
    ) -> AsyncIterator[str]:
        """
        Streaming variant — yields raw text chunks from the LLM.

        The caller receives raw token strings; the final answer must be
        assembled client-side. Sources, follow-ups, and intent are sent
        as a separate terminal JSON object prefixed with "\n__META__:".

        Usage (FastAPI):
            async for chunk in generator.generate_stream(req):
                yield chunk
        """
        query              = request.query
        source_filter      = request.source_filter
        jurisdiction_filter = request.jurisdiction_filter

        # Parallel: intent + retrieval
        intent, results = await asyncio.gather(
            self._intent_classifier.classify(query),
            self._retrieve(query, source_filter, jurisdiction_filter),
        )

        context_str, sources = build_context(results, intent)
        top_score = retrieval_confidence(results)

        use_web = should_use_web_search(top_score, intent.value, self.WEB_SEARCH_SCORE_THRESHOLD)
        web_query: Optional[str] = None
        web_formatted = ""

        if use_web:
            web_query = build_web_search_query(query, intent.value)
            web_formatted, _ = await web_search(web_query)

        pv = active_version()
        if context_str and not use_web:
            user_prompt = get_prompt("user_with_context", pv).format(
                context_blocks=context_str, query=query
            )
        elif use_web and web_formatted:
            user_prompt = get_prompt("user_with_web", pv).format(
                web_query=web_query, web_results=web_formatted, query=query
            )
        else:
            user_prompt = get_prompt("user_no_context", pv).format(query=query)

        system_prompt = get_system_prompt(intent.value, pv)

        stream = await self._client.chat.completions.create(
            model=self._model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_prompt},
            ],
            max_tokens=settings.llm_max_tokens,
            temperature=settings.llm_temperature,
            stream=True,
            # JSON mode not available in streaming; model is prompted to output JSON
        )

        async for chunk in stream:
            delta = chunk.choices[0].delta.content
            if delta:
                yield delta

        # Emit structured metadata after the stream ends
        meta = {
            "intent":           intent.value,
            "sources":          [s.model_dump() for s in sources],
            "used_web_search":  use_web and bool(web_formatted),
            "web_search_query": web_query,
            "retrieval_used":   bool(context_str),
        }
        yield f"\n__META__:{json.dumps(meta)}"
